from django.db import models


class Country(models.Model):
    c_1   = models.CharField(max_length=50)
    c_2   = models.CharField(max_length=1000)
    ph_1  = models.ForeignKey("Population")
    ph_2  = models.FloatField()
    ph_3  = models.FloatField()
    ph_4  = models.IntegerField()
    ph_5  = models.ForeignKey("PopulationLiving")
    ph_6  = models.FloatField()
    ph_7  = models.FloatField()
    ph_8  = models.FloatField()
    ph_9  = models.ForeignKey("LifeExpectancy")
    ph_10 = models.IntegerField()
    ph_11 = models.IntegerField()
    ph_12 = models.IntegerField()
    ph_13 = models.IntegerField()
    ph_14 = models.IntegerField()
    ph_15 = models.ForeignKey("BirthsAttended")
    ph_16 = models.ForeignKey("AntenatalCareOne")
    ph_17 = models.ForeignKey("AntenatalCareFour")
    ph_18 = models.FloatField()
    ph_19 = models.ForeignKey("PostnatalCare")
    ph_20 = models.CharField(max_length=50)
    ph_21 = models.CharField(max_length=50)
    av_1  = models.IntegerField()
    av_2  = models.IntegerField()
    av_3  = models.IntegerField()
    av_4  = models.IntegerField()
    av_5  = models.IntegerField()
    av_5a = models.IntegerField()
    av_6  = models.IntegerField()
    av_7  = models.FloatField()
    av_8  = models.CharField(max_length=10)
    av_9  = models.FloatField()
    av_10 = models.CharField(max_length=10)
    av_11 = models.FloatField()
    av_12 = models.CharField(max_length=10)
    as_1  = models.FloatField()
    as_2  = models.FloatField()
    as_3  = models.FloatField()
    ap_1  = models.CharField(max_length=10)
    ap_2  = models.FloatField()
    ap_3  = models.FloatField()
    qu_1  = models.CharField(max_length=10)
    qu_2  = models.CharField(max_length=10)
    qu_3  = models.CharField(max_length=10)
    qu_4  = models.CharField(max_length=10)
    qu_5  = models.CharField(max_length=10)
    qu_6  = models.CharField(max_length=10)
    qu_7  = models.CharField(max_length=10)
    qu_8  = models.CharField(max_length=10)
    qu_9  = models.CharField(max_length=10)
    qu_10 = models.CharField(max_length=10)
    qu_11 = models.CharField(max_length=10)
    qu_12 = models.CharField(max_length=10)
    qu_13 = models.CharField(max_length=10)
    qu_14 = models.CharField(max_length=10)
    qu_15 = models.CharField(max_length=10)
    ps_1  = models.CharField(max_length=10)
    ps_2  = models.CharField(max_length=10)
    ps_3  = models.CharField(max_length=10)
    ps_4  = models.CharField(max_length=10)
    ps_5  = models.CharField(max_length=10)
    ps_6  = models.CharField(max_length=10)
    ps_7  = models.CharField(max_length=10)
    ps_8  = models.CharField(max_length=10)
    ps_9  = models.CharField(max_length=10)
    ps_10 = models.CharField(max_length=10)
    ps_11 = models.CharField(max_length=10)

class Population(models.Model):
    all_population = models.FloatField()
    under_15 = models.IntegerField()
    over_60 = models.IntegerField()

class PopulationLiving(models.Model):
    population = models.FloatField()
    year =  models.IntegerField()

class LifeExpectancy(models.Model):
    all_population = models.IntegerField()
    female_population = models.IntegerField()
    male_population =  models.IntegerField()

class BirthsAttended(models.Model):
    attended = models.FloatField()
    year = models.IntegerField()

class AntenatalCareOne(models.Model):
    antenatal_care = models.FloatField()
    year = models.IntegerField()

class AntenatalCareFour(models.Model):
    antenatal_care = models.FloatField()
    year = models.IntegerField()

class PostnatalCare(models.Model):
    postnatal_care = models.FloatField()
    year = models.IntegerField()

